
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.16.2
 * Query Engine version: 1c57fdcd7e44b29b9313256c76699e91c3ac3c43
 */
Prisma.prismaVersion = {
  client: "6.16.2",
  engine: "1c57fdcd7e44b29b9313256c76699e91c3ac3c43"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sku: 'sku',
  barcode: 'barcode',
  internationalName: 'internationalName',
  category: 'category',
  categoryId: 'categoryId',
  manufacturer: 'manufacturer',
  countryOfOrigin: 'countryOfOrigin',
  manufacturerId: 'manufacturerId',
  dosage: 'dosage',
  dosageUnit: 'dosageUnit',
  formId: 'formId',
  packageTypeId: 'packageTypeId',
  totalStock: 'totalStock',
  minStock: 'minStock',
  costPrice: 'costPrice',
  sellingPrice: 'sellingPrice',
  status: 'status',
  isActive: 'isActive',
  image: 'image',
  prescription: 'prescription',
  markingRequired: 'markingRequired',
  analogs: 'analogs',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BatchScalarFieldEnum = {
  id: 'id',
  batchNumber: 'batchNumber',
  quantity: 'quantity',
  initialQty: 'initialQty',
  currentQty: 'currentQty',
  reservedQty: 'reservedQty',
  availableQty: 'availableQty',
  unit: 'unit',
  costBasis: 'costBasis',
  purchasePrice: 'purchasePrice',
  wholesalePrice: 'wholesalePrice',
  retailPrice: 'retailPrice',
  supplierId: 'supplierId',
  warehouseId: 'warehouseId',
  manufacturedDate: 'manufacturedDate',
  receivedAt: 'receivedAt',
  expiryDate: 'expiryDate',
  status: 'status',
  productId: 'productId',
  purchaseItemId: 'purchaseItemId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BatchMovementScalarFieldEnum = {
  id: 'id',
  type: 'type',
  quantity: 'quantity',
  date: 'date',
  description: 'description',
  batchId: 'batchId',
  userId: 'userId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  name: 'name',
  role: 'role',
  isActive: 'isActive',
  warehouseId: 'warehouseId',
  lastLoginAt: 'lastLoginAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  contact: 'contact',
  email: 'email',
  address: 'address',
  contractNumber: 'contractNumber',
  contractDate: 'contractDate',
  paymentTermDays: 'paymentTermDays',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNo: 'invoiceNo',
  customer: 'customer',
  totalAmount: 'totalAmount',
  taxAmount: 'taxAmount',
  discount: 'discount',
  paymentType: 'paymentType',
  status: 'status',
  paymentStatus: 'paymentStatus',
  comment: 'comment',
  userId: 'userId',
  cashShiftId: 'cashShiftId',
  customerId: 'customerId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceItemScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  productId: 'productId',
  batchId: 'batchId',
  productName: 'productName',
  batchNo: 'batchNo',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  discountAmount: 'discountAmount',
  totalPrice: 'totalPrice'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  userRole: 'userRole',
  module: 'module',
  action: 'action',
  entity: 'entity',
  entityId: 'entityId',
  oldValue: 'oldValue',
  newValue: 'newValue',
  reason: 'reason',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.WarehouseScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  type: 'type',
  address: 'address',
  isDefault: 'isDefault',
  isActive: 'isActive',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WarehouseStockScalarFieldEnum = {
  id: 'id',
  warehouseId: 'warehouseId',
  productId: 'productId',
  quantity: 'quantity',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockTransferScalarFieldEnum = {
  id: 'id',
  transferNo: 'transferNo',
  fromWarehouseId: 'fromWarehouseId',
  toWarehouseId: 'toWarehouseId',
  status: 'status',
  reason: 'reason',
  createdById: 'createdById',
  receivedById: 'receivedById',
  createdAt: 'createdAt',
  receivedAt: 'receivedAt'
};

exports.Prisma.StockTransferItemScalarFieldEnum = {
  id: 'id',
  transferId: 'transferId',
  productId: 'productId',
  batchId: 'batchId',
  quantity: 'quantity'
};

exports.Prisma.ReturnScalarFieldEnum = {
  id: 'id',
  returnNo: 'returnNo',
  type: 'type',
  status: 'status',
  warehouseId: 'warehouseId',
  invoiceId: 'invoiceId',
  supplierId: 'supplierId',
  customerId: 'customerId',
  customerName: 'customerName',
  refundMethod: 'refundMethod',
  reason: 'reason',
  note: 'note',
  totalAmount: 'totalAmount',
  approvedById: 'approvedById',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReturnItemScalarFieldEnum = {
  id: 'id',
  returnId: 'returnId',
  productId: 'productId',
  batchId: 'batchId',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  discountAmount: 'discountAmount',
  lineTotal: 'lineTotal',
  reason: 'reason',
  invoiceItemId: 'invoiceItemId'
};

exports.Prisma.WriteOffScalarFieldEnum = {
  id: 'id',
  writeOffNo: 'writeOffNo',
  warehouseId: 'warehouseId',
  reason: 'reason',
  status: 'status',
  note: 'note',
  totalAmount: 'totalAmount',
  createdById: 'createdById',
  approvedById: 'approvedById',
  createdAt: 'createdAt'
};

exports.Prisma.WriteOffItemScalarFieldEnum = {
  id: 'id',
  writeOffId: 'writeOffId',
  productId: 'productId',
  batchId: 'batchId',
  quantity: 'quantity',
  unitCost: 'unitCost',
  lineTotal: 'lineTotal'
};

exports.Prisma.CashShiftScalarFieldEnum = {
  id: 'id',
  shiftNo: 'shiftNo',
  warehouseId: 'warehouseId',
  cashierId: 'cashierId',
  status: 'status',
  openingCash: 'openingCash',
  closingCash: 'closingCash',
  expectedCash: 'expectedCash',
  discrepancy: 'discrepancy',
  openAt: 'openAt',
  closeAt: 'closeAt',
  closeNote: 'closeNote'
};

exports.Prisma.CashMovementScalarFieldEnum = {
  id: 'id',
  shiftId: 'shiftId',
  userId: 'userId',
  type: 'type',
  amount: 'amount',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.PriceHistoryScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  type: 'type',
  oldValue: 'oldValue',
  newValue: 'newValue',
  effectiveFrom: 'effectiveFrom',
  changedById: 'changedById',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.ProductCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ManufacturerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  country: 'country',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductFormScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PackageTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseInvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  supplierId: 'supplierId',
  warehouseId: 'warehouseId',
  invoiceDate: 'invoiceDate',
  status: 'status',
  totalAmount: 'totalAmount',
  discountAmount: 'discountAmount',
  taxAmount: 'taxAmount',
  paymentStatus: 'paymentStatus',
  comment: 'comment',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseInvoiceItemScalarFieldEnum = {
  id: 'id',
  purchaseInvoiceId: 'purchaseInvoiceId',
  productId: 'productId',
  batchNumber: 'batchNumber',
  manufacturedDate: 'manufacturedDate',
  quantity: 'quantity',
  packPrice: 'packPrice',
  unitPrice: 'unitPrice',
  total: 'total',
  lineDiscount: 'lineDiscount',
  lineTotal: 'lineTotal'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  direction: 'direction',
  counterpartyType: 'counterpartyType',
  supplierId: 'supplierId',
  method: 'method',
  amount: 'amount',
  paymentDate: 'paymentDate',
  status: 'status',
  referenceNumber: 'referenceNumber',
  invoiceId: 'invoiceId',
  purchaseInvoiceId: 'purchaseInvoiceId',
  createdById: 'createdById',
  customerId: 'customerId',
  comment: 'comment',
  createdAt: 'createdAt'
};

exports.Prisma.PayableScalarFieldEnum = {
  id: 'id',
  supplierId: 'supplierId',
  purchaseInvoiceId: 'purchaseInvoiceId',
  originalAmount: 'originalAmount',
  paidAmount: 'paidAmount',
  remainingAmount: 'remainingAmount',
  dueDate: 'dueDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductAliasScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  supplierId: 'supplierId',
  alias: 'alias'
};

exports.Prisma.ProductAnalogScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  analogProductId: 'analogProductId',
  similarityNote: 'similarityNote'
};

exports.Prisma.OcrDocumentScalarFieldEnum = {
  id: 'id',
  documentNo: 'documentNo',
  supplierId: 'supplierId',
  uploadedById: 'uploadedById',
  fileName: 'fileName',
  mimeType: 'mimeType',
  status: 'status',
  rawText: 'rawText',
  normalizedJson: 'normalizedJson',
  invoiceNumber: 'invoiceNumber',
  invoiceDate: 'invoiceDate',
  duplicateOfId: 'duplicateOfId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OcrRowScalarFieldEnum = {
  id: 'id',
  documentId: 'documentId',
  lineNo: 'lineNo',
  rawLine: 'rawLine',
  productName: 'productName',
  sku: 'sku',
  barcode: 'barcode',
  quantity: 'quantity',
  unit: 'unit',
  purchasePrice: 'purchasePrice',
  total: 'total',
  batchNumber: 'batchNumber',
  expiryDate: 'expiryDate',
  matchedProductId: 'matchedProductId',
  confidence: 'confidence',
  warnings: 'warnings',
  needsReview: 'needsReview'
};

exports.Prisma.OcrImportDraftScalarFieldEnum = {
  id: 'id',
  documentId: 'documentId',
  approvedById: 'approvedById',
  summary: 'summary',
  imported: 'imported',
  rolledBack: 'rolledBack',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BackupMetadataScalarFieldEnum = {
  id: 'id',
  fileName: 'fileName',
  filePath: 'filePath',
  checksum: 'checksum',
  sizeBytes: 'sizeBytes',
  isAuto: 'isAuto',
  status: 'status',
  createdById: 'createdById',
  createdAt: 'createdAt'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  category: 'category',
  amount: 'amount',
  note: 'note',
  warehouseId: 'warehouseId',
  recordedById: 'recordedById',
  date: 'date'
};

exports.Prisma.SupplierPayableScalarFieldEnum = {
  id: 'id',
  supplierId: 'supplierId',
  amount: 'amount',
  type: 'type',
  referenceNo: 'referenceNo',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  legalName: 'legalName',
  phone: 'phone',
  email: 'email',
  address: 'address',
  taxId: 'taxId',
  managerName: 'managerName',
  creditLimit: 'creditLimit',
  defaultDiscount: 'defaultDiscount',
  paymentTermDays: 'paymentTermDays',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReceivableScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  customerId: 'customerId',
  customerName: 'customerName',
  originalAmount: 'originalAmount',
  paidAmount: 'paidAmount',
  remainingAmount: 'remainingAmount',
  dueDate: 'dueDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReservationScalarFieldEnum = {
  id: 'id',
  batchId: 'batchId',
  quantity: 'quantity',
  status: 'status',
  expiredAt: 'expiredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.ProductStatus = exports.$Enums.ProductStatus = {
  ACTIVE: 'ACTIVE',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK'
};

exports.BatchStatus = exports.$Enums.BatchStatus = {
  CRITICAL: 'CRITICAL',
  STABLE: 'STABLE',
  NEAR_EXPIRY: 'NEAR_EXPIRY',
  EXPIRED: 'EXPIRED'
};

exports.BatchMovementType = exports.$Enums.BatchMovementType = {
  RESTOCK: 'RESTOCK',
  DISPATCH: 'DISPATCH',
  ADJUSTMENT: 'ADJUSTMENT',
  RETURN: 'RETURN',
  WRITE_OFF: 'WRITE_OFF',
  TRANSFER_OUT: 'TRANSFER_OUT',
  TRANSFER_IN: 'TRANSFER_IN'
};

exports.UserRole = exports.$Enums.UserRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  CASHIER: 'CASHIER',
  PHARMACIST: 'PHARMACIST',
  WAREHOUSE_STAFF: 'WAREHOUSE_STAFF'
};

exports.PaymentType = exports.$Enums.PaymentType = {
  CASH: 'CASH',
  CARD: 'CARD',
  CREDIT: 'CREDIT',
  STORE_BALANCE: 'STORE_BALANCE'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  PAID: 'PAID',
  PENDING: 'PENDING',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED',
  PARTIALLY_RETURNED: 'PARTIALLY_RETURNED',
  RESERVED: 'RESERVED'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  UNPAID: 'UNPAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};

exports.TransferStatus = exports.$Enums.TransferStatus = {
  DRAFT: 'DRAFT',
  IN_TRANSIT: 'IN_TRANSIT',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED'
};

exports.ReturnType = exports.$Enums.ReturnType = {
  CUSTOMER: 'CUSTOMER',
  SUPPLIER: 'SUPPLIER'
};

exports.ReturnStatus = exports.$Enums.ReturnStatus = {
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.RefundMethod = exports.$Enums.RefundMethod = {
  CASH: 'CASH',
  CARD: 'CARD',
  STORE_BALANCE: 'STORE_BALANCE'
};

exports.WriteOffReason = exports.$Enums.WriteOffReason = {
  EXPIRED: 'EXPIRED',
  DAMAGED: 'DAMAGED',
  LOST: 'LOST',
  INTERNAL_USE: 'INTERNAL_USE',
  MISMATCH: 'MISMATCH',
  BROKEN_PACKAGING: 'BROKEN_PACKAGING',
  OTHER: 'OTHER'
};

exports.ShiftStatus = exports.$Enums.ShiftStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
};

exports.CashMovementType = exports.$Enums.CashMovementType = {
  CASH_IN: 'CASH_IN',
  CASH_OUT: 'CASH_OUT'
};

exports.PriceType = exports.$Enums.PriceType = {
  PURCHASE: 'PURCHASE',
  WHOLESALE: 'WHOLESALE',
  RETAIL: 'RETAIL'
};

exports.PurchaseInvoiceStatus = exports.$Enums.PurchaseInvoiceStatus = {
  DRAFT: 'DRAFT',
  POSTED: 'POSTED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
};

exports.PaymentDirection = exports.$Enums.PaymentDirection = {
  IN: 'IN',
  OUT: 'OUT'
};

exports.CounterpartyType = exports.$Enums.CounterpartyType = {
  SUPPLIER: 'SUPPLIER',
  OTHER: 'OTHER',
  CUSTOMER: 'CUSTOMER'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER'
};

exports.DebtStatus = exports.$Enums.DebtStatus = {
  OPEN: 'OPEN',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  WRITTEN_OFF: 'WRITTEN_OFF'
};

exports.OcrDocumentStatus = exports.$Enums.OcrDocumentStatus = {
  UPLOADED: 'UPLOADED',
  PARSED: 'PARSED',
  MATCHED: 'MATCHED',
  PARTIALLY_MATCHED: 'PARTIALLY_MATCHED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  IMPORTED: 'IMPORTED',
  FAILED: 'FAILED',
  ROLLED_BACK: 'ROLLED_BACK'
};

exports.OcrConfidence = exports.$Enums.OcrConfidence = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

exports.Prisma.ModelName = {
  Product: 'Product',
  Batch: 'Batch',
  BatchMovement: 'BatchMovement',
  User: 'User',
  Supplier: 'Supplier',
  Invoice: 'Invoice',
  InvoiceItem: 'InvoiceItem',
  AuditLog: 'AuditLog',
  Warehouse: 'Warehouse',
  WarehouseStock: 'WarehouseStock',
  StockTransfer: 'StockTransfer',
  StockTransferItem: 'StockTransferItem',
  Return: 'Return',
  ReturnItem: 'ReturnItem',
  WriteOff: 'WriteOff',
  WriteOffItem: 'WriteOffItem',
  CashShift: 'CashShift',
  CashMovement: 'CashMovement',
  PriceHistory: 'PriceHistory',
  ProductCategory: 'ProductCategory',
  Manufacturer: 'Manufacturer',
  ProductForm: 'ProductForm',
  PackageType: 'PackageType',
  PurchaseInvoice: 'PurchaseInvoice',
  PurchaseInvoiceItem: 'PurchaseInvoiceItem',
  Payment: 'Payment',
  Payable: 'Payable',
  ProductAlias: 'ProductAlias',
  ProductAnalog: 'ProductAnalog',
  OcrDocument: 'OcrDocument',
  OcrRow: 'OcrRow',
  OcrImportDraft: 'OcrImportDraft',
  BackupMetadata: 'BackupMetadata',
  Expense: 'Expense',
  SupplierPayable: 'SupplierPayable',
  Customer: 'Customer',
  Receivable: 'Receivable',
  Reservation: 'Reservation'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
